### ISSUE TITLE
Hasura claims for roles are hardcoded

### ISSUE THREAD

**Issue by mikeslattery** [CkCreative/hasura_gotrue#2]
[Role and roles are hard-coded](https://github.com/CkCreative/hasura_gotrue/blob/9b2787cb3546d1ec54b6bcf626835ff335bd7c10/gotrue/api/token.go#L174) to `"user"` and `"user","vendor"`.  This means I can't effectively use role-based permissions in Hasura.

They should come instead come from `user.AppMetaData["roles"]`

**Comment by CkCreative** [comment]
Feel free to create a pull request Mike, I will merge so other users will benefit. I haven't had time to look at this project recently. Thanks

**Comment by mikeslattery** [comment]
I think this ticket can be closed in lieu of #3

@CkCreative I'll let you close this, if you want to.

**Comment by mikeslattery** [comment]
Closing in lieu of #3   This project is unnecessary with proper hasura configuration.
